batch_size = 16
rollouts_per_example = 16
seq_len = 2048
max_steps = 100
max_async_level = 5

[model]
# SFT model
name = "outputs/sft/weights/step_100"

[sampling]
max_tokens = 128

[[env]]
id = 'reverse_text'
