max_steps = 20
max_async_level = 5
batch_size = 128
seq_len = 8192

[client]
base_url = ["http://localhost:8000/v1", "http://localhost:8001/v1", "http://localhost:8002/v1", "http://localhost:8003/v1"]

[sampling]
max_tokens = 350
