max_steps = 100
loss_impl = "liger"

[model]
name = "PrimeIntellect/Qwen3-8B"
impl = "liger_kernel"

[data]
name = "willcb/R1-reverse-wikipedia-paragraphs-v1-1000"
batch_size = 32
seq_len = 4096

[optim]
lr = 2e-5
