max_steps = 100

[model]
name = "PrimeIntellect/Qwen3-0.6B"

[data]
type = "sft"
name = "willcb/R1-reverse-wikipedia-paragraphs-v1-1000"
batch_size = 16
seq_len = 1024
micro_batch_size = 1

[optim]
lr = 2e-6
